<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="118288" started-at="2018-01-12T14:04:34Z" finished-at="2018-01-12T14:06:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="118288" started-at="2018-01-12T14:04:34Z" finished-at="2018-01-12T14:06:32Z">
      <class name="testcases.TC003_Registration_General">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcases.TC003_Registration_General@ef9176]" name="beforeSuite" is-config="true" duration-ms="717" started-at="2018-01-12T19:34:33Z" finished-at="2018-01-12T19:34:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testcases.TC003_Registration_General@ef9176]" name="beforeTest" is-config="true" duration-ms="6" started-at="2018-01-12T19:34:34Z" finished-at="2018-01-12T19:34:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="setValue()[pri:0, instance:testcases.TC003_Registration_General@ef9176]" name="setValue" is-config="true" duration-ms="0" started-at="2018-01-12T19:34:34Z" finished-at="2018-01-12T19:34:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setValue -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.TC003_Registration_General@ef9176]" name="beforeMethod" is-config="true" duration-ms="13866" started-at="2018-01-12T19:34:35Z" finished-at="2018-01-12T19:34:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="generalUserRegistration(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.TC003_Registration_General@ef9176]" name="generalUserRegistration" duration-ms="103326" started-at="2018-01-12T19:34:49Z" data-provider="fetchData" finished-at="2018-01-12T19:36:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[General]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sugumaar]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Devaraj]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Chennai Main Road]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[TamilNadu]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Chennai*]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Male]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[9638527410]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[raja10@gmail.com]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="10">
              <value>
                <![CDATA[You are successfully registered,information will be sent to your email.Please continue using the same account for Causelist website & App!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: FAILED
	at utils.Reporter.reportStep(Reporter.java:33)
	at utils.Reporter.reportStep(Reporter.java:43)
	at wrappers.GenericWrappers.verifyTextContainsByXpath(GenericWrappers.java:245)
	at pages.RegistrationPage.verifyPopupAlertDetails(RegistrationPage.java:135)
	at testcases.TC003_Registration_General.generalUserRegistration(TC003_Registration_General.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generalUserRegistration -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.TC003_Registration_General@ef9176]" name="afterMethod" is-config="true" duration-ms="147" started-at="2018-01-12T19:36:32Z" finished-at="2018-01-12T19:36:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testcases.TC003_Registration_General@ef9176]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-01-12T19:36:32Z" finished-at="2018-01-12T19:36:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testcases.TC003_Registration_General@ef9176]" name="afterSuite" is-config="true" duration-ms="423" started-at="2018-01-12T19:36:32Z" finished-at="2018-01-12T19:36:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.TC003_Registration_General -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
