<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testcases.TC001_Loginnegative" tests="1" time="0.000" ignored="4" failures="0" timestamp="21 Dec 2017 08:04:50 GMT" skipped="0" hostname="maxpro11" errors="1">
  <testcase name="loginLogOut" time="0.000" classname="testcases.TC001_Loginnegative">
    <error type="org.testng.TestNGException" message="
Data Provider public java.lang.Object[][] wrappers.LeafTapsWrappers.getData() must return either Object[][] or Iterator&lt;Object&gt;[], not class [[Ljava.lang.Object;">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.Object[][] wrappers.LeafTapsWrappers.getData() must return either Object[][] or Iterator<Object>[], not class [[Ljava.lang.Object;
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:133)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- loginLogOut -->
  <testcase name="beforeTest" classname="wrappers.LeafTapsWrappers">
    <skipped/>
  </testcase> <!-- beforeTest -->
  <testcase name="afterSuite" classname="wrappers.LeafTapsWrappers">
    <skipped/>
  </testcase> <!-- afterSuite -->
  <testcase name="beforeSuite" classname="wrappers.LeafTapsWrappers">
    <skipped/>
  </testcase> <!-- beforeSuite -->
  <testcase name="afterTest" classname="wrappers.LeafTapsWrappers">
    <skipped/>
  </testcase> <!-- afterTest -->
</testsuite> <!-- testcases.TC001_Loginnegative -->
